name: Checks and tests

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Check encoding
        run: |
          OIFS="$IFS"
          IFS=$'\n'
          FAILURE_FILES=''
          RETURN_CODE=0
          FILES=`find ./src -name '*.*'`
          FILES="$FILES"$'\n'"./pom.xml"
          for f in $FILES
          do
            echo Check $f
            file -bi $f | grep -iE 'charset=(utf-8)|(us-ascii)' > /dev/null || FAILURE_FILES="$FAILURE_FILES"$'\n'"$f"
          done
          for f in $FAILURE_FILES
          do
            printf [ER
            echo ROR] $f
            RETURN_CODE=-1
          done
          IFS=$OIFS
          exit $RETURN_CODE
      - name: Check line separators
        run: |
          OIFS="$IFS"
          IFS=$'\n'
          FAILURE_FILES=''
          RETURN_CODE=0
          FILES=`find ./src -name '*.*'`
          FILES="$FILES"$'\n'"./pom.xml"
          for f in $FILES
          do
            echo Check $f
            cat -e $f | grep -E '\^M\$?$' > /dev/null && FAILURE_FILES="$FAILURE_FILES"$'\n'"$f"
          done
          for f in $FAILURE_FILES
          do
            printf [ER
            echo ROR] $f
            RETURN_CODE=-1
          done
          IFS=$OIFS
          exit $RETURN_CODE
      - name: Check codestyle
        run: mvn checkstyle:check
      - name: Pack jar with tests
        run: mvn package
