name: Java CI with Maven

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: |
          date +%s > report.txt
          git status
      - name: Commit report
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
        run: |
          git add ./report.txt
          git -c "user.name=Github Actions" -c "user.email=zhivaev993@gmail.com" commit -m "Automated report"
          git push
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#      - name: Sample step
#        run: ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
#      - name: Update build number
#        shell: bash
#        run: |
#          ./scripts/bash/ci_increment_build_number.sh
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#          git push
