name: Build and test

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Check line separators
        run: |
          OIFS="$IFS"
          IFS=$'\n'
          FAILURE_FILES=''
          RETURN_CODE=0
          FILES=`find ./src -name '*.java' -or -name '*.xml'`
          echo
          for f in $FILES
          do
            echo check $f
            cat -e $f | grep -E '\^M\$?$' > /dev/null && FAILURE_FILES="${FAILURE_FILES} ${f}"
          done
          for f in $FAILURE_FILES
          do
            printf [ER
            echo ROR] $f
            RETURN_CODE=-1
          done
          IFS=$OIFS
          exit $RETURN_CODE
      - name: Pack jar with tests
        run: mvn package
